USE master;

if exists (select * from sysdatabases where name='FLIGHTS')
	DROP DATABASE subscription;

CREATE DATABASE subscription;

USE subscription;

------TABLES------
CREATE TABLE [USER](
ID INT PRIMARY KEY,
EMAIL VARCHAR(200) UNIQUE NOT NULL ,
PASSWORD VARCHAR(200) CHECK(LEN(PASSWORD) > 8) NOT NULL,
NAME VARCHAR(200) NOT NULL,
F_ATT INT DEFAULT 0 CHECK (F_ATT IN (0,1,2,3)) NOT NULL,
AGE INT NOT NULL,
GENDER CHAR CHECK (GENDER IN ('m', 'f')),
COUNTRY_ID INT NOT NULL);

CREATE TABLE PRODUCT(
ID INT PRIMARY KEY,
NAME VARCHAR(200) NOT NULL,
TYPE_ID INT NOT NULL,
MIN_AGE INT NOT NULL,
ORIGIN_COUNTRY_ID INT NOT NULL); 

CREATE TABLE SUBSCRIPTION(
ID INT PRIMARY KEY, 
USER_ID INT NOT NULL, 
DURATION INT NOT NULL,
PROD_SUB_PR_ID INT NOT NULL );

CREATE TABLE DEBIT_CARD(
ID INT PRIMARY KEY,
USER_ID INT NOT NULL,
NUMBER INT NOT NULL UNIQUE CHECK(LEN(NUMBER) = 16),
EXP_DATE DATE NOT NULL);


CREATE TABLE USER_LIKES(
PRODUCT_ID INT NOT NULL ,
USER_ID INT NOT NULL 
PRIMARY KEY(PRODUCT_ID,USER_ID)
);

CREATE TABLE COUNTRY (
ID INT PRIMARY KEY,
NAME VARCHAR(200) NOT NULL UNIQUE);

CREATE TABLE DIST_COUNTRY (
PRODUCT_ID INT NOT NULL ,    
COUNTRY_ID INT NOT NULL,   
PRIMARY KEY(PRODUCT_ID,COUNTRY_ID)
);   

CREATE TABLE PRODUCT_SUBS_PRICE (
ID INT PRIMARY KEY,
PRODUCT_ID INT NOT NULL,
SUBS_TYPE_ID INT, 
PRICE INT NOT NULL
);

CREATE TABLE COMMENT (
ID INT PRIMARY KEY,
USER_ID INT NOT NULL,
PRODUCT_ID INT NOT NULL,
TEXT VARCHAR(1000) NOT NULL);

CREATE TABLE SUBS_TYPE(
ID INT PRIMARY KEY,
NAME VARCHAR(10) CHECK (NAME IN ('online', 'physical'))
);

CREATE TABLE GENRE (
ID INT PRIMARY KEY,
NAME VARCHAR(50) UNIQUE NOT NULL);

CREATE TABLE TYPE (
ID INT PRIMARY KEY,
NAME VARCHAR(10) NOT NULL,
GENRE_ID INT NOT NULL);


---FOREIGN KEYS-----

ALTER TABLE [USER] ADD CONSTRAINT FK_USER_COUNTRY FOREIGN KEY(COUNTRY_ID) REFERENCES COUNTRY(ID);

ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_TYPE FOREIGN KEY(TYPE_ID) REFERENCES TYPE(ID);
ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_COUNTRY FOREIGN KEY(ORIGIN_COUNTRY_ID) REFERENCES COUNTRY(ID);

ALTER TABLE SUBSCRIPTION ADD CONSTRAINT FK_SUBSCRIPTION_USER FOREIGN KEY(USER_ID) REFERENCES [USER](ID);
ALTER TABLE SUBSCRIPTION ADD CONSTRAINT FK_SUBSCRIPTION_PRODUCT_SUBS_PRICE FOREIGN KEY(PROD_SUB_PR_ID) REFERENCES PRODUCT_SUBS_PRICE(ID);

ALTER TABLE DEBIT_CARD ADD CONSTRAINT FK_DEBIT_CARD_USER FOREIGN KEY(USER_ID) REFERENCES [USER](ID);

ALTER TABLE USER_LIKES ADD CONSTRAINT FK_USER_LIKES_PRODUCT FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID);
ALTER TABLE USER_LIKES ADD CONSTRAINT FK_USER_LIKES_USER FOREIGN KEY(USER_ID) REFERENCES [USER](ID);

ALTER TABLE DIST_COUNTRY ADD CONSTRAINT FK_DIST_COUNTRY_PRODUCT FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID);
ALTER TABLE DIST_COUNTRY ADD CONSTRAINT FK_DIST_COUNTRY_COUNTRY FOREIGN KEY(COUNTRY_ID) REFERENCES COUNTRY(ID);

ALTER TABLE PRODUCT_SUBS_PRICE ADD CONSTRAINT FK_PRODUCT_SUBS_PRICE_PRODUCT FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID);
ALTER TABLE PRODUCT_SUBS_PRICE ADD CONSTRAINT FK_PRODUCT_SUBS_PRICE_SUBS_TYPE FOREIGN KEY(SUBS_TYPE_ID) REFERENCES SUBS_TYPE(ID);

ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_USER FOREIGN KEY(USER_ID) REFERENCES [USER](ID);
ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_PRODUCT FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID);

