USE master;
GO

CREATE DATABASE TODOTASKS;
GO

USE TODOTASKS;
GO

CREATE TABLE TODOTASKS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME VARCHAR(300) NOT NULL,
	DESCRIPTION VARCHAR(500) NOT NULL,
	DATE DATETIME NOT NULL,
	DONE BIT NOT NULL,
	ASSIGNMENT_ID INT NOT NULL
);
GO

CREATE TABLE ASSIGNMENTS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	CREATED_BY VARCHAR(50) NOT NULL,
	ASSIGNED_TO VARCHAR(50) NOT NULL
);
GO

ALTER TABLE TODOTASKS ADD CONSTRAINT FK_TODOTASKS_ASSIGNMENTS FOREIGN KEY(ASSIGNMENT_ID) REFERENCES ASSIGNMENTS(ID);
GO