USE master

if exists (select * from sysdatabases where name='TODOTASKS')
	DROP DATABASE TODOTASKS

CREATE DATABASE TODOTASKS

USE TODOTASKS

-------Create Tables --------

CREATE TABLE TODOTASKS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME VARCHAR(300) NOT NULL,
	DESCRIPTION VARCHAR(500) NOT NULL,
	DATE DATETIME NOT NULL,
	DONE BIT NOT NULL,
	ASSIGNMENT_ID INT NOT NULL
);

CREATE TABLE ASSIGNMENTS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	CREATED_BY_ID INT NOT NULL,
	ASSIGNED_TO_ID INT NOT NULL,
);

CREATE TABLE PEOPLE(
    ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME VARCHAR(300) NOT NULL,
	AGE INT NOT NULL
	);

------Add Foreign Keys-------

ALTER TABLE TODOTASKS ADD CONSTRAINT FK_TODOTASKS_ASSIGNMENTS FOREIGN KEY(ASSIGNMENT_ID) REFERENCES ASSIGNMENTS(ID);
ALTER TABLE ASSIGNMENTS ADD CONSTRAINT FK_ASSIGNMENTS_CREATED_BY FOREIGN KEY(CREATED_BY_ID) REFERENCES PEOPLE(ID);
ALTER TABLE ASSIGNMENTS ADD CONSTRAINT FK_ASSIGNMENTS_ASSIGNED_TO FOREIGN KEY(ASSIGNED_TO_ID) REFERENCES PEOPLE(ID);

------Insert Initial Tasks------

INSERT INTO PEOPLE (NAME, AGE) 
VALUES ('Simona', 23);

INSERT INTO PEOPLE (NAME, AGE) 
VALUES ('Jane', 30);

INSERT INTO PEOPLE (NAME, AGE) 
VALUES ('John', 80);

INSERT INTO ASSIGNMENTS (CREATED_BY_ID, ASSIGNED_TO_ID) 
VALUES (1, 2);

INSERT INTO ASSIGNMENTS (CREATED_BY_ID, ASSIGNED_TO_ID) 
VALUES (3, 2);

INSERT INTO ASSIGNMENTS (CREATED_BY_ID, ASSIGNED_TO_ID) 
VALUES (1, 3);

INSERT INTO TODOTASKS (NAME, DESCRIPTION, DATE, DONE, ASSIGNMENT_ID)
VALUES ('Walk the dinosaur', 'It is time he gets a decent snack', GETDATE(), 0, 1);

INSERT INTO TODOTASKS (NAME, DESCRIPTION, DATE, DONE, ASSIGNMENT_ID)
VALUES ('Teach the cow to fly', 'With a parachute, of course', GETDATE(), 0, 2);

INSERT INTO TODOTASKS (NAME, DESCRIPTION, DATE, DONE, ASSIGNMENT_ID)
VALUES ('Get 8 hours of sleep', 'Six hours of sleep will do wonders, too', GETDATE(), 0, 3);