// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ToDoTaskSolution.Entities;

[Table("ASSIGNMENTS")]
public partial class Assignment
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("CREATED_BY_ID")]
    public int CreatedById { get; set; }

    [Column("ASSIGNED_TO_ID")]
    public int AssignedToId { get; set; }

    [ForeignKey("AssignedToId")]
    [InverseProperty("AssignmentAssignedTos")]
    public virtual Person AssignedTo { get; set; }

    [ForeignKey("CreatedById")]
    [InverseProperty("AssignmentCreatedBies")]
    public virtual Person CreatedBy { get; set; }

    [InverseProperty("Assignment")]
    public virtual ICollection<Todotask> Todotasks { get; set; } = new List<Todotask>();
}