// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using ToDoTaskSolution.Entities.Constants;

namespace ToDoTaskSolution.Entities;

[Table("PEOPLE")]
public partial class Person
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [Column("NAME")]
    [MinLength(DataConstants.PERSON_NAME_LEN_MIN, ErrorMessage = "User name must be at least {1} symbols.")]
    [StringLength(DataConstants.PERSON_NAME_LEN_MAX, ErrorMessage = "User name must be shorter than {2} symbols.")]
    [Unicode(false)]
    public string Name { get; set; }

    [Range(DataConstants.PERSON_AGE_MIN,DataConstants.PERSON_AGE_MAX, ErrorMessage = "Age must be between {1} and {2}.")]
    [Column("AGE")]
    public int Age { get; set; }

    [InverseProperty("AssignedTo")]
    public virtual ICollection<Assignment> AssignmentAssignedTos { get; set; } = new List<Assignment>();

    [InverseProperty("CreatedBy")]
    public virtual ICollection<Assignment> AssignmentCreatedBies { get; set; } = new List<Assignment>();
}