// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ToDoTaskSolution.Entities;

[Table("PEOPLE")]
public partial class Person
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [Column("NAME")]
    [StringLength(300)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("AGE")]
    public int Age { get; set; }

    [InverseProperty("AssignedTo")]
    public virtual ICollection<Assignment> AssignmentAssignedTos { get; set; } = new List<Assignment>();

    [InverseProperty("CreatedBy")]
    public virtual ICollection<Assignment> AssignmentCreatedBies { get; set; } = new List<Assignment>();
}