// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using ToDoTaskSolution.Entities.Constants;

namespace ToDoTaskSolution.Entities;

[Table("TODOTASKS")]
public partial class Todotask
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [Column("NAME")]
    [MinLength(DataConstants.TASK_NAME_LEN_MIN, ErrorMessage = "Task Name must be longer than {1} symbols.")]
    [StringLength(DataConstants.TASK_NAME_LEN_MAX, ErrorMessage = "Task Name must be shorter than {2} symbols.")]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [Column("DESCRIPTION")]
    [MinLength(DataConstants.TASK_DESCRIPTION_LEN_MIN, ErrorMessage = "Task Description must be longer than {1} symbols.")]
    [StringLength(DataConstants.TASK_DESCRIPTION_LEN_MAX, ErrorMessage = "Task Description must be shorter than {2} symbols.")]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("DATE", TypeName = "datetime")]
    public DateTime Date { get; set; }

    [Column("DONE")]
    public bool Done { get; set; }

    [Column("ASSIGNMENT_ID")]
    public int AssignmentId { get; set; }

    [ForeignKey("AssignmentId")]
    [InverseProperty("Todotasks")]
    public virtual Assignment Assignment { get; set; }
}