// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ToDoTaskSolution.Entities;

[Table("TODOTASKS")]
public partial class Todotask
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [Column("NAME")]
    [StringLength(300)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [Column("DESCRIPTION")]
    [StringLength(500)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("DATE", TypeName = "datetime")]
    public DateTime Date { get; set; }

    [Column("DONE")]
    public bool Done { get; set; }

    [Column("ASSIGNMENT_ID")]
    public int AssignmentId { get; set; }

    [ForeignKey("AssignmentId")]
    [InverseProperty("Todotasks")]
    public virtual Assignment Assignment { get; set; }
}