// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ToDoTaskSolution.Entities;

public partial class TODOTASKSContext : DbContext
{
    public TODOTASKSContext()
    {
    }

    public TODOTASKSContext(DbContextOptions<TODOTASKSContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Assignment> Assignments { get; set; }

    public virtual DbSet<Todotask> Todotasks { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Server=sql-server-db,1433;Database=TODOTASKS;User ID=sa;Password=YourStrong@Passw0rd; Trust Server certificate=True;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Assignment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ASSIGNME__3214EC272718617B");
        });

        modelBuilder.Entity<Todotask>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TODOTASK__3214EC273CD4E09E");

            entity.HasOne(d => d.Assignment).WithMany(p => p.Todotasks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TODOTASKS_ASSIGNMENTS");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}